### ISSUE TITLE
Automatic versioning in sourcecode

### ISSUE THREAD

**Issue by andreasdahl1987** [andreasdahl1987/DahlDesignProperties#13]
I was wondering, is there a way to automate the versioning in the .cs file, as well as in a .json file in the dashboard? 

When we build a new release we have to type in the new version number. It would be really slick if this process also could change the version property in the plugin as well as the version check in the dashboard. 

Possible? @mcowger @photon1503

**Comment by mcowger** [comment]
It's possible - but I'm not sure how to do it in VS.  will have to research.

**Comment by photon1503** [comment]
I think the version should be defined in Properties\AssemblyInfo.cs
Currently it's set to _[assembly: AssemblyVersion("1.0.0.0")]_ and this version is also shown if you check the "details" tab on the DLL in Windows File Explorer.

This version could be automatically read out by some github action, i.e. https://github.com/marketplace/actions/create-the-version-string

We could also set the SimHub Property DahlDesign.Version from above value by reading _Assembly.GetName().Version_

So this approach is the other way around as your proposal.

But I don't see any possibility on the Dashboard since there is no support for versions in SimHub, I think a manual update is necessary for each release.

**Comment by andreasdahl1987** [comment]
@photon1503 
Ok, if I understand you correctly, what you're explaining is the "proper" way to make a version of the plugin and read out the plugin version in gitHub and in SimHub. And it seems like GitHub can set the version number on release to whatever we write in the AssemblyInfo.cs file?

**Comment by photon1503** [comment]
@andreasdahl1987 
exactly, but I am not sure if it's worth it to be honest.

**Comment by andreasdahl1987** [comment]
@photon1503 Agree, the workflow would be pretty much the same, it is just more work setting it all up.
